# -*- coding: utf-8 -*-
"""test_gen_corutine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kl4apaHY7lthlKAQwkjaAK0b152xFPFF
"""

# Генератор

def get_count(start = 1, step = 1):
  counter = start
  while True:
    yield counter
    counter += step

# Запускает цикл и проверяем функцию
for i in get_count(1, 1500):
  print(i)

# Фибоначи гинератор

def get_fib():
  yield 0
  a, b = 1, 1
  yield a
  yield b
  while True:
    a, b = b, a + b
    yield b 

# Запускает цикл и проверяем функцию
test = get_fib()
for i in test:
  print(i)

# Карутины

def get_grep(pattern):
  i = 0
  while True:
    line = yield
    if pattern in line:
      i += 1
      print(f'Pattern {pattern} was here ! i: {i}')

g = get_grep('Hello')
next(g)
g.send('Test')
g.send('Test Hello')

